import type { Metadata } from "next";
import "./globals.css";

import { QueryProvider } from "@/providers/query-provider";
import InstallPrompt from "@/components/pwa/install-prompt";
import UpdatePrompt from "@/components/pwa/update-prompt";
import SplashScreen from "@/components/pwa/splash-screen";
import { splashGateScript } from "@/components/pwa/splash-gate";
import { darbare } from "@/lib/utils";


export const metadata: Metadata = {
  title: "آکادمی آموزش برنامه نویسی و هوش مصنوعی آیوهوش",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="fa-IR"
      dir="rtl"
      className={`${darbare.variable}  h-full antialiased`}
      // data-splash را اسکریپت زیر قبل از hydrate تنظیم می‌کند.
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: splashGateScript }} />
      </head>
      <body className="min-h-full flex flex-col items-center">
        <SplashScreen />
        <QueryProvider>{children}

          <InstallPrompt />
          <UpdatePrompt />
        </QueryProvider>
      </body>
    </html>
  );
}
