import type { Metadata } from "next";
import "./globals.css";

import { QueryProvider } from "@/providers/query-provider";

import { darbare } from "@/lib/utils";


export const metadata: Metadata = {
  title: "آکادمی آموزش برنامه نویسی و هوش مصنوعی آیوهوش",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="fa-IR"
      dir="rtl"
      className={`${darbare.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col items-center">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
